### ISSUE TITLE
Error after migrating from node 14.17.5 to 16.13.1.

### ISSUE THREAD

**Issue by parloti** [zirkelc/git-pull-run#2]
SO: Windows 10
I tested it several times in both versions of node to be sure of the cause of the error.

The command:
`npx git-pull-run -p \"package-lock.json\" -c \"npm\ install\"`

Failed with the following error:

Error: Cannot find module '**_C:\Users\xelaspt\Dev\refin-alt_\node_modules\npm\bin\npm-cli.js**'
**C:\Users\xelaspt\Dev\refin-alt** ist my project path.

This one works:
`npx git-pull-run -p \"package-lock.json\" -c C:\\Progra~1\\nodejs\\npm\ install`

**Log:**
```
$ npx git-pull-run -p \"package-lock.json\" -c \"npm\ install\" --debug
  git-pull-run Started git-pull-run@1.0.2 +0ms
  git-pull-run:getGitDirectory Get git directory +0ms
  git-pull-run:runGit Running git 'git rev-parse --show-toplevel' +0ms
C:/Users/xelaspt/Dev/refin-alt
  git-pull-run:runGit Git command executed with exit code: 0 +318ms
  git-pull-run:getGitDirectory Git directory: C:/Users/xelaspt/Dev/refin-alt +319ms
  git-pull-run:getChanges Get changed files +0ms
  git-pull-run:runGit Running git 'git diff --name-only HEAD@{1} HEAD' +1ms        
...
  git-pull-run:runGit Git command executed with exit code: 0 +330ms
  git-pull-run:getChanges Changed files: [
  ... 32 more items
] +331ms
  git-pull-run:getChanges Match files with pattern '"package-lock.json"': [ 'package-lock.json' ] +31ms
  git-pull-run Found 1 change for pattern '"package-lock.json"' +0ms
  git-pull-run:getAbsolutePath Absolute path resolved: C:\Users\xelaspt\Dev\refin-alt +0ms
  git-pull-run Running command '"npm install"' for change 'package-lock.json' in directory C:\Users\xelaspt\Dev\refin-alt... +4ms
  git-pull-run:runCommand Running command '"npm install"' in directory 'C:\Users\xelaspt\Dev\refin-alt' +0ms
  git-pull-run:runCommand Command failed with exit code: 1 +1s
error Error: Command failed with exit code 1: "npm install"
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '**C:\Users\xelaspt\Dev\refin-alt\node_modules\npm\bin\npm-cli.js**'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\xelaspt\Dev\refin-alt\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
    at runCommand (file:///C:/Users/xelaspt/Dev/refin-alt/node_modules/git-pull-run/dist/runCommand.js:17:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async gitPullRun (file:///C:/Users/xelaspt/Dev/refin-alt/node_modules/git-pull-run/dist/index.js:25:32)
  git-pull-run Finished git-pull-run@1.0.2 +2s
```

**Comment by parloti** [comment]
Looks like the problem was the quotes.

This works:
`npx git-pull-run -p \"package-lock.json\" -c npm\ install`
